# Generated by Django 5.0.3 on 2024-03-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('biensoxe', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=20)),
                ('ngaygui', models.DateTimeField(auto_now_add=True)),
                ('tinhtrang', models.CharField(max_length=50)),
                ('thanhtoan', models.CharField(max_length=50)),
            ],
        ),
    ]
